#!/usr/bin/bash
# An "apply_extra" script gets automatically executed after "extra-data" are downloaded during
# installation. CWD is at /app/extra/.

# The errexit is the reason why this script is not embeded directly in the app manifest
set -o errexit -o pipefail

# Uncomment this when debugging, comment out for a final release. The output would otherwise be
# also shown to end-users when installing on a command line, which would look bad.
#set -o verbose
#set -o xtrace

tar xf FFS.tar.gz
test "$(ls -1 FreeFileSync*.run | wc -l)" -eq 1
mv FreeFileSync*.run FreeFileSync_Install.run
7z x -oFFS_Installer_Archive FreeFileSync_Install.run >/dev/null
test -d FFS_Installer_Archive
mkdir FreeFileSync
tar xf FFS_Installer_Archive/FreeFileSync.tar.gz --directory FreeFileSync

rm -rf FFS_Installer_Archive
rm FreeFileSync_Install.run
rm FFS.tar.gz

rm 'FreeFileSync/User Manual.pdf'

# Check whether the target binary actually exists (test -f resolves symlinks)
test -f /app/bin/FreeFileSync
test -f /app/bin/RealTimeSync
